import type { SiteUiContent } from "@/types/site-content";
import { allClientServices, clientServiceCategories } from "@/lib/client-services";
import { categoryLabels } from "@/lib/content";

export const defaultUiContent: SiteUiContent = {
  skipToContent: "Pular para o conteúdo",
  loader: {
    kicker: "INICIALIZANDO",
    name: "MDS SOLUÇÕES",
    hint: "Carregando interface…",
  },
  scrollTop: "Voltar ao topo",
  nav: {
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    brandAria: "MDS Soluções em Tecnologia, início",
    languageLabel: "Idioma do site",
    chooseLanguage: "Escolher idioma",
  },
  homeServices: {
    eyebrow: "Serviços",
    title: "Tudo que sua empresa precisa em tecnologia",
    lead: "Do site ao ERP, com código sob medida e suporte próximo.",
    learnMore: "Saiba mais",
    items: [
      {
        title: "Desenvolvimento Web",
        desc: "Sites, landing pages e portais com performance e SEO.",
        href: "/servicos",
      },
      {
        title: "Sistemas & ERP",
        desc: "Gestão de vendas, estoque, financeiro e integrações.",
        href: "/servicos",
      },
      {
        title: "Aplicativos",
        desc: "Apps mobile e PWAs conectados ao seu negócio.",
        href: "/servicos",
      },
      {
        title: "Assistência Técnica",
        desc: "Infraestrutura, manutenção e suporte empresarial.",
        href: "/servicos",
      },
    ],
  },
  homeProcess: {
    eyebrow: "Como trabalhamos",
    title: "Do primeiro contato à entrega",
    steps: [
      { title: "Briefing", text: "Escopo, stack e prazos alinhados com você." },
      { title: "Proposta", text: "Orçamento claro com entregas e cronograma." },
      { title: "Desenvolvimento", text: "Código versionado e entregas por etapa." },
      { title: "Suporte", text: "Monitoramento e evolução contínua." },
    ],
  },
  homeCta: {
    eyebrow: "Próximo passo",
    title: "Pronto para começar?",
    lead: "Monte seu orçamento online ou fale com nosso time.",
    clientArea: "Área do Cliente",
    contact: "Contato",
  },
  homeFeatured: {
    eyebrow: "Portfólio",
    title: "Projetos em produção",
    lead: "Interfaces e sistemas reais por segmento.",
    viewAll: "Ver todos",
  },
  portfolio: {
    filterAll: "Todos",
  },
  clientQuote: {
    eyebrow: "Área do Cliente",
    title: "Monte seu orçamento",
    lead:
      'Escolha uma categoria para ver o catálogo. Marque os serviços e eles aparecem em "Produtos selecionados" ao lado.',
    catalogTitle: "Catálogo",
    catalogHint: "Clique em uma aba para exibir os serviços.",
    tabAll: "Todos",
    tabAllServices: "Todos os serviços",
    showingPrefix: "Exibindo:",
    itemsSuffix: "itens",
    emptyCategory: "Nenhum serviço nesta categoria.",
    selectedTitle: "Produtos selecionados",
    selectedEmpty: "Nenhum serviço ainda. Abra uma categoria e marque os itens desejados.",
    formTitle: "Seus dados",
    nameLabel: "Nome *",
    namePlaceholder: "Seu nome",
    emailLabel: "E-mail *",
    emailPlaceholder: "seu@email.com",
    phoneLabel: "Telefone",
    phonePlaceholder: "(17) 99999-9999",
    companyLabel: "Empresa",
    companyPlaceholder: "Opcional",
    urgencyLabel: "Urgência",
    urgencyNormal: "Normal (2 a 4 semanas)",
    urgencyUrgent: "Urgente",
    urgencyFlexible: "Flexível",
    budgetLabel: "Orçamento (opcional)",
    budgetPlaceholder: "Ex: até R$ 5.000",
    detailsLabel: "Detalhes do projeto",
    detailsPlaceholder: "Descreva o projeto...",
    sendWhatsapp: "Enviar pelo WhatsApp",
    sendEmail: "Enviar por e-mail",
    validationHint: "Selecione ao menos um serviço e preencha nome e e-mail válido.",
    sentWhatsapp: "WhatsApp aberto!",
    sentEmail: "E-mail aberto!",
    removeService: "Remover",
  },
  clientServiceCategories,
  clientServices: allClientServices,
  categoryLabels,
};
